# Generated by Django 5.2.4 on 2025-08-09 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcbuilder', '0003_alter_user_managers_alter_user_avatar_and_more'),
    ]

    operations = [
        # Drop unique_together on BuildComponent before removing its fields
        migrations.AlterUniqueTogether(
            name='buildcomponent',
            unique_together=None,
        ),
        # Now safely remove FKs and related fields
        migrations.RemoveField(
            model_name='buildcomponent',
            name='build',
        ),
        migrations.RemoveField(
            model_name='buildcomponent',
            name='component',
        ),
        migrations.RemoveField(
            model_name='component',
            name='category',
        ),
        migrations.RemoveField(
            model_name='compatibilityrule',
            name='target',
        ),
        migrations.RemoveField(
            model_name='compatibilityrule',
            name='source',
        ),
        migrations.RemoveField(
            model_name='component',
            name='vendor',
        ),
        # Finally delete ORM models no longer used in lean mode
        migrations.DeleteModel(
            name='Build',
        ),
        migrations.DeleteModel(
            name='BuildComponent',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='CompatibilityRule',
        ),
        migrations.DeleteModel(
            name='Component',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
