# Generated by Django 5.2.4 on 2025-08-09 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcbuilder', '0004_remove_buildcomponent_build_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_pro_builder',
        ),
    ]
